Attaching to a433-microservices_item-app_1, a433-microservices_item-db_1
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m > docker-software-delivery@1.0.0 start /app
[36mitem-app_1  |[0m > node ./bin/www
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m NODE_ENV: production
[36mitem-app_1  |[0m Connected to database
[36mitem-app_1  |[0m [0mGET / [32m200 [0m140.485 ms - 785[0m
[36mitem-app_1  |[0m [0mGET /javascripts/dist/dist.min.js [36m304 [0m3.275 ms - -[0m
[36mitem-app_1  |[0m [0mGET /stylesheets/style.css [32m200 [0m39.037 ms - 519[0m
[36mitem-app_1  |[0m [0mGET /api [32m200 [0m11.434 ms - 2[0m
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m > docker-software-delivery@1.0.0 start /app
[36mitem-app_1  |[0m > node ./bin/www
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m NODE_ENV: production
[36mitem-app_1  |[0m Connected to database
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m > docker-software-delivery@1.0.0 start /app
[36mitem-app_1  |[0m > node ./bin/www
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m NODE_ENV: production
[36mitem-app_1  |[0m /app/node_modules/mongodb/lib/mongo_client.js:421
[36mitem-app_1  |[0m           throw err
[36mitem-app_1  |[0m           ^
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 172.26.0.2:27017
[36mitem-app_1  |[0m     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
[36mitem-app_1  |[0m   name: 'MongoError'
[36mitem-app_1  |[0m }]
[36mitem-app_1  |[0m     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[36mitem-app_1  |[0m     at Pool.emit (events.js:400:28)
[36mitem-app_1  |[0m     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[36mitem-app_1  |[0m     at Object.onceWrapper (events.js:520:26)
[36mitem-app_1  |[0m     at Connection.emit (e...
[36mitem-app_1  |[0m     at /app/app.js:24:10
[36mitem-app_1  |[0m     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
[36mitem-app_1  |[0m     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
[36mitem-app_1  |[0m     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
[36mitem-app_1  |[0m   generatedMessage: true,
[36mitem-app_1  |[0m   code: 'ERR_ASSERTION',
[36mitem-app_1  |[0m   actual: null,
[36mitem-app_1  |[0m   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 172.26.0.2:27017
[36mitem-app_1  |[0m       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
[36mitem-app_1  |[0m     name: 'MongoError'
[36mitem-app_1  |[0m   }]
[36mitem-app_1  |[0m       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[36mitem-app_1  |[0m       at Pool.emit (events.js:400:28)
[36mitem-app_1  |[0m       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[36mitem-app_1  |[0m       at Object.onceWrapper (events.js:520:26)
[36mitem-app_1  |[0m       at Connection.emit (events.js:400:28)
[36mitem-app_1  |[0m       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
[36mitem-app_1  |[0m       at Object.onceWrapper (events.js:520:26)
[36mitem-app_1  |[0m       at Socket.emit (events.js:400:28)
[36mitem-app_1  |[0m       at emitErrorNT (internal/streams/destroy.js:106:8)
[36mitem-app_1  |[0m       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
[36mitem-app_1  |[0m   operator: '=='
[36mitem-app_1  |[0m }
[36mitem-app_1  |[0m npm ERR! code ELIFECYCLE
[36mitem-app_1  |[0m npm ERR! errno 1
[36mitem-app_1  |[0m npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
[36mitem-app_1  |[0m npm ERR! Exit status 1
[36mitem-app_1  |[0m npm ERR! 
[36mitem-app_1  |[0m npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
[36mitem-app_1  |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m npm ERR! A complete log of this run can be found in:
[36mitem-app_1  |[0m npm ERR!     /root/.npm/_logs/2022-11-29T12_18_58_760Z-debug.log
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m > docker-software-delivery@1.0.0 start /app
[36mitem-app_1  |[0m > node ./bin/www
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m NODE_ENV: production
[36mitem-app_1  |[0m Connected to database
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=3fe9a0026c55
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten] db version v3.6.23
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten] git version: d352e6a4764659e0d0350ce77279de3c1f243e5c
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten] modules: none
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten] build environment:
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten]     distarch: x86_64
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten]     target_arch: x86_64
[33mitem-db_1   |[0m 2022-11-29T12:16:44.940+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
[33mitem-db_1   |[0m 2022-11-29T12:16:44.942+0000 I STORAGE  [initandlisten] 
[33mitem-db_1   |[0m 2022-11-29T12:16:44.942+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[33mitem-db_1   |[0m 2022-11-29T12:16:44.942+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[33mitem-db_1   |[0m 2022-11-29T12:16:44.942+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=256M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
[33mitem-db_1   |[0m 2022-11-29T12:16:46.164+0000 I STORAGE  [initandlisten] WiredTiger message [1669724206:164173][1:0x7f3240e56a40], txn-recover: Set global recovery timestamp: 0
[33mitem-db_1   |[0m 2022-11-29T12:16:46.179+0000 I CONTROL  [initandlisten] 
[33mitem-db_1   |[0m 2022-11-29T12:16:46.179+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[33mitem-db_1   |[0m 2022-11-29T12:16:46.179+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[33mitem-db_1   |[0m 2022-11-29T12:16:46.179+0000 I CONTROL  [initandlisten] 
[33mitem-db_1   |[0m 2022-11-29T12:16:46.179+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 366830fa-c498-4f52-a96b-bef882d6debf
[33mitem-db_1   |[0m 2022-11-29T12:16:46.186+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.6
[33mitem-db_1   |[0m 2022-11-29T12:16:46.186+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 405a80c2-d976-492a-9ccd-989bf5de4ccc
[33mitem-db_1   |[0m 2022-11-29T12:16:46.193+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[33mitem-db_1   |[0m 2022-11-29T12:16:46.193+0000 I NETWORK  [initandlisten] listening via socket bound to 0.0.0.0
[33mitem-db_1   |[0m 2022-11-29T12:16:46.194+0000 I NETWORK  [initandlisten] listening via socket bound to /tmp/mongodb-27017.sock
[33mitem-db_1   |[0m 2022-11-29T12:16:46.194+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
[33mitem-db_1   |[0m 2022-11-29T12:16:46.194+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: 885ac446-d5d4-48c7-8ada-a375926add13
[33mitem-db_1   |[0m 2022-11-29T12:16:46.203+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
[33mitem-db_1   |[0m 2022-11-29T12:16:46.203+0000 I INDEX    [LogicalSessionCacheRefresh] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
[33mitem-db_1   |[0m 2022-11-29T12:16:46.203+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
[33mitem-db_1   |[0m 2022-11-29T12:16:46.433+0000 I NETWORK  [listener] connection accepted from 172.26.0.3:57160 #1 (1 connection now open)
[33mitem-db_1   |[0m 2022-11-29T12:16:46.438+0000 I NETWORK  [conn1] received client metadata from 172.26.0.3:57160 conn1: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.0-126-generic" }, platform: "Node.js v14.21.1, LE, mongodb-core: 2.1.20" }
[33mitem-db_1   |[0m 2022-11-29T12:18:40.497+0000 I NETWORK  [conn1] end connection 172.26.0.3:57160 (0 connections now open)
[33mitem-db_1   |[0m 2022-11-29T12:18:51.612+0000 I NETWORK  [listener] connection accepted from 172.26.0.3:54812 #2 (1 connection now open)
[33mitem-db_1   |[0m 2022-11-29T12:18:51.618+0000 I NETWORK  [conn2] received client metadata from 172.26.0.3:54812 conn2: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.0-126-generic" }, platform: "Node.js v14.21.1, LE, mongodb-core: 2.1.20" }
[33mitem-db_1   |[0m 2022-11-29T12:18:52.712+0000 I NETWORK  [conn2] end connection 172.26.0.3:54812 (0 connections now open)
[33mitem-db_1   |[0m 2022-11-29T12:18:52.859+0000 I CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
[33mitem-db_1   |[0m 2022-11-29T12:18:52.859+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
[33mitem-db_1   |[0m 2022-11-29T12:18:52.859+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
[33mitem-db_1   |[0m 2022-11-29T12:18:52.859+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
[33mitem-db_1   |[0m 2022-11-29T12:18:52.861+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
[33mitem-db_1   |[0m 2022-11-29T12:18:52.908+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
[33mitem-db_1   |[0m 2022-11-29T12:18:52.908+0000 I CONTROL  [signalProcessingThread] now exiting
[33mitem-db_1   |[0m 2022-11-29T12:18:52.909+0000 I CONTROL  [signalProcessingThread] shutting down with code:0
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=3fe9a0026c55
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten] db version v3.6.23
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten] git version: d352e6a4764659e0d0350ce77279de3c1f243e5c
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten] modules: none
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten] build environment:
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten]     distarch: x86_64
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten]     target_arch: x86_64
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I STORAGE  [initandlisten] 
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[33mitem-db_1   |[0m 2022-11-29T12:18:57.146+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=256M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
[33mitem-db_1   |[0m 2022-11-29T12:18:58.742+0000 I STORAGE  [initandlisten] WiredTiger message [1669724338:742372][1:0x7ff199d74a40], txn-recover: Main recovery loop: starting at 1/22272
[33mitem-db_1   |[0m 2022-11-29T12:18:58.965+0000 I STORAGE  [initandlisten] WiredTiger message [1669724338:965879][1:0x7ff199d74a40], txn-recover: Recovering log 1 through 2
[33mitem-db_1   |[0m 2022-11-29T12:18:59.106+0000 I STORAGE  [initandlisten] WiredTiger message [1669724339:106453][1:0x7ff199d74a40], txn-recover: Recovering log 2 through 2
[33mitem-db_1   |[0m 2022-11-29T12:18:59.233+0000 I STORAGE  [initandlisten] WiredTiger message [1669724339:233475][1:0x7ff199d74a40], txn-recover: Set global recovery timestamp: 0
[33mitem-db_1   |[0m 2022-11-29T12:18:59.283+0000 I CONTROL  [initandlisten] 
[33mitem-db_1   |[0m 2022-11-29T12:18:59.283+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[33mitem-db_1   |[0m 2022-11-29T12:18:59.283+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[33mitem-db_1   |[0m 2022-11-29T12:18:59.283+0000 I CONTROL  [initandlisten] 
[33mitem-db_1   |[0m 2022-11-29T12:18:59.294+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[33mitem-db_1   |[0m 2022-11-29T12:18:59.294+0000 I NETWORK  [initandlisten] listening via socket bound to 0.0.0.0
[33mitem-db_1   |[0m 2022-11-29T12:18:59.294+0000 I NETWORK  [initandlisten] listening via socket bound to /tmp/mongodb-27017.sock
[33mitem-db_1   |[0m 2022-11-29T12:18:59.294+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
[33mitem-db_1   |[0m 2022-11-29T12:18:59.940+0000 I NETWORK  [listener] connection accepted from 172.26.0.3:56258 #1 (1 connection now open)
[33mitem-db_1   |[0m 2022-11-29T12:18:59.945+0000 I NETWORK  [conn1] received client metadata from 172.26.0.3:56258 conn1: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.0-126-generic" }, platform: "Node.js v14.21.1, LE, mongodb-core: 2.1.20" }
